/**
 * Wren token usage tracking — server-side only.
 *
 * Two Firestore docs per user:
 *   /users/{uid}/usage/daily      -> { day: "YYYY-MM-DD" (in the user's own timezone), tokens }
 *   /users/{uid}/usage/conv_{cid} -> { tokens }
 *
 * The daily doc resets automatically the first time it's read/written on a new
 * calendar day *in that user's own timezone* (matches how Settings already
 * computes "today" elsewhere in the codebase) — no cron job needed.
 *
 * Limits are checked BEFORE a request is allowed to call any AI provider (so a
 * blocked request costs nothing), and usage is recorded AFTER a call actually
 * succeeds, using the real token counts the provider returned. This means the
 * one call that pushes a user over the limit is still allowed to finish — the
 * NEXT request after that is what gets blocked. Simple, and avoids guessing at
 * token cost before a call has even happened.
 */

export const DAILY_TOKEN_LIMIT = 100_000;
export const CONVERSATION_TOKEN_LIMIT = 40_000;

export type UsageStatus = {
  dailyTokens: number;
  conversationTokens: number;
  blocked: false | "daily" | "conversation";
};

function todayIn(timezone: string): string {
  return new Intl.DateTimeFormat("en-CA", { timeZone: timezone, year: "numeric", month: "2-digit", day: "2-digit" }).format(new Date());
}

// Conversation ids should already be safe (alphanumeric, generated by newConversationId),
// but strip anything that isn't safe in a Firestore document id just in case.
function safeCid(cid: string): string {
  return cid.replace(/[^a-zA-Z0-9_-]/g, "").slice(0, 100) || "unknown";
}

function docUrl(projectId: string, uid: string, docId: string) {
  return `https://firestore.googleapis.com/v1/projects/${projectId}/databases/(default)/documents/users/${uid}/usage/${docId}`;
}

async function readTokenDoc(projectId: string, uid: string, docId: string, idToken: string): Promise<number> {
  try {
    const res = await fetch(docUrl(projectId, uid, docId), {
      headers: { Authorization: `Bearer ${idToken}` },
      signal: AbortSignal.timeout(5000),
    });
    if (!res.ok) return 0;
    const doc = await res.json();
    const v = doc?.fields?.tokens?.integerValue;
    return typeof v === "string" ? parseInt(v, 10) : typeof v === "number" ? v : 0;
  } catch {
    return 0;
  }
}

async function readDailyDoc(projectId: string, uid: string, idToken: string, timezone: string): Promise<number> {
  try {
    const res = await fetch(docUrl(projectId, uid, "daily"), {
      headers: { Authorization: `Bearer ${idToken}` },
      signal: AbortSignal.timeout(5000),
    });
    if (!res.ok) return 0;
    const doc = await res.json();
    const day = doc?.fields?.day?.stringValue;
    const tokens = doc?.fields?.tokens?.integerValue;
    if (day !== todayIn(timezone)) return 0; // new day — counter has reset
    return typeof tokens === "string" ? parseInt(tokens, 10) : typeof tokens === "number" ? tokens : 0;
  } catch {
    return 0;
  }
}

/** Read current usage and say whether a new request should be allowed to proceed. */
export async function checkUsage(uid: string, cid: string, idToken: string, timezone: string): Promise<UsageStatus> {
  const projectId = process.env.NEXT_PUBLIC_FIREBASE_PROJECT_ID;
  if (!projectId) return { dailyTokens: 0, conversationTokens: 0, blocked: false };

  const [dailyTokens, conversationTokens] = await Promise.all([
    readDailyDoc(projectId, uid, idToken, timezone),
    readTokenDoc(projectId, uid, `conv_${safeCid(cid)}`, idToken),
  ]);

  const blocked: UsageStatus["blocked"] =
    dailyTokens >= DAILY_TOKEN_LIMIT ? "daily" : conversationTokens >= CONVERSATION_TOKEN_LIMIT ? "conversation" : false;

  return { dailyTokens, conversationTokens, blocked };
}

/** Add tokens from a completed call to both the daily and conversation counters. Best-effort — a failure here never blocks the reply the user already got. */
export async function recordUsage(uid: string, cid: string, idToken: string, timezone: string, tokens: number): Promise<void> {
  if (tokens <= 0) return;
  const projectId = process.env.NEXT_PUBLIC_FIREBASE_PROJECT_ID;
  if (!projectId) return;

  const write = async (docId: string, fields: Record<string, { stringValue?: string; integerValue?: string }>, mask: string[]) => {
    try {
      const q = mask.map((k) => `updateMask.fieldPaths=${k}`).join("&");
      await fetch(`${docUrl(projectId, uid, docId)}?${q}`, {
        method: "PATCH",
        headers: { "Content-Type": "application/json", Authorization: `Bearer ${idToken}` },
        body: JSON.stringify({ fields }),
        signal: AbortSignal.timeout(5000),
      });
    } catch { /* best-effort */ }
  };

  const day = todayIn(timezone);
  const [existingDaily, existingConv] = await Promise.all([
    readDailyDoc(projectId, uid, idToken, timezone),
    readTokenDoc(projectId, uid, `conv_${safeCid(cid)}`, idToken),
  ]);

  await Promise.all([
    write("daily", { day: { stringValue: day }, tokens: { integerValue: String(existingDaily + tokens) } }, ["day", "tokens"]),
    write(`conv_${safeCid(cid)}`, { tokens: { integerValue: String(existingConv + tokens) } }, ["tokens"]),
  ]);
}

export function limitMessage(blocked: "daily" | "conversation"): string {
  return blocked === "daily"
    ? "You've reached today's testing limit for Wren. It resets at midnight your time — thanks for helping test!"
    : "This conversation has used up its testing limit. Start a new chat to keep going — thanks for helping test!";
}